language: ruby
rvm:
- 2.1.4
sudo: false
cache: bundler
install: bundle install
script:
- bundle exec jekyll build
- bundle exec htmlproof _site
deploy:
- provider: s3
  access_key_id: AKIAJTIRCVHLYE6JUEIQ
  secret_access_key:
    secure: GzVVe+WOhssy7RSzjQ8dqMDG1hMcbKTILdXQOemaTZdcKMEuFjBz+iUKmSSxt6M7xIMbEBVR8sZYLv7zL7dH4mByTN1RjStktuhzYBUSTlgY3gdyF8UXKiJC2iDbe+lemcTQ2hgaahDvwMiNIDUrddZIzFY359fc6g//LltAURM=
  bucket: staging.never-a-bad.com
  local-dir: _site
  skip_cleanup: true
  on:
    branch: develop
- provider: s3
  access_key_id: AKIAJTIRCVHLYE6JUEIQ
  secret_access_key:
    secure: GzVVe+WOhssy7RSzjQ8dqMDG1hMcbKTILdXQOemaTZdcKMEuFjBz+iUKmSSxt6M7xIMbEBVR8sZYLv7zL7dH4mByTN1RjStktuhzYBUSTlgY3gdyF8UXKiJC2iDbe+lemcTQ2hgaahDvwMiNIDUrddZIzFY359fc6g//LltAURM=
  bucket: www.never-a-bad.com
  local-dir: _site
  skip_cleanup: true
  on:
    branch: master
