# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            never a bad
tagline:          'never.'
description:      "And what I most can't the least would be do not a bad job, but always a good."
url:              http://www.never-a-bad.com
baseurl:          /

author:
  name:           'Nicholas Campanini/Javier Campanini'
  url:

paginate:         5

# Custom vars
version:          0.1.1

github:
  repo:

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
